modLoader="javafml"
loaderVersion="[1,)"
license="GPL-3.0"
issueTrackerURL="${mod_website}/issues"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="${mod_website}"
logoFile="assets/toastbegone/icon.png"
credits=""
authors="${mod_author}"
description="${mod_description}"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21.0.0-beta,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.21,1.21.1)"
ordering="NONE"
side="BOTH"